openapi: 3.0.1
# http://localhost:8080/static/sample3.0/index.yaml

info:
  title: Sample API
  description: API description in Markdown. ..
  version: 1.0.0

servers:
- url: 'https://api.example.com'

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
    dkdk :
      summary: 1111
      deprecated: 1

