swagger: "2.0"

info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: api.example.com
basePath: /v1
schemes:
- https

consumes:
  - application/json
  - application/xml

produces:
  - application/json
  - application/xml

#asd:
#  asdf: 22

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
      - application/json
      responses:
        200:
          description: OK
#    kiki :
#      summary: 1
#      description: 1



