openapi: 3.0.1

info:
  title: Guard API
  description: >-
    API description in Markdown.
  version: 0.0.1

servers:
- url: 'http://localhost:9999'
  description: LOCAL
- url: 'http://dev.avocadostudio.com:9999'
  description: DEV
- url: 'http://localhost:5555/api/guard'
  description: Gateway - LOCAL
- url: 'http://dev.avocadostudio.com:5555/api/guard'
  description: Gateway - DEV

paths:
  /apps:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
  /apps/{appId}:
    get:
      summary:
      operationId:
      parameters:
        -
      responses:
    post:
      summary:
      operationId:
      parameters:
        -
      responses:
    put:
      summary:
      operationId:
      parameters:
        -
      responses:
    delete:
      summary:
      operationId:
      parameters:
        -
      responses:




